SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (1, 1, 'DNH', 1, NULL, 0, 'DNH - 0/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (2, 2, 'DEP', 1, NULL, 1, 'DEP - 1/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (2, 3, 'DEP', 1, NULL, 30, 'DEP - 30/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (2, 4, 'DEP', 1, NULL, 0, 'DEP - 45/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (2, 5, 'DEP', 1, NULL, 30, 'DEP - 60/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (2, 6, 'DEP', 2, NULL, 30, 'DEP - 30/60/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (2, 7, 'DEP', 3, NULL, 30, 'DEP - 30/60/90/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (3, 8, 'BOL', 1, NULL, 1, 'BOL - 15/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (3, 9, 'BOL', 1, NULL, 1, 'BOL - 20/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (3, 10, 'BOL', 1, NULL, 2, 'BOL - 28/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (3, 11, 'BOL', 1, NULL, 1, 'BOL - 30/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (3, 12, 'BOL', 1, NULL, 1, 'BOL - 45/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (3, 13, 'BOL', 2, NULL, 20, 'BOL - 20/40/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (3, 14, 'BOL', 2, NULL, 14, 'BOL - 28/42/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (3, 15, 'BOL', 2, NULL, 28, 'BOL - 28/56/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (3, 16, 'BOL', 2, NULL, 30, 'BOL - 30/60/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (3, 17, 'BOL', 3, NULL, 20, 'BOL - 20/40/60/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (3, 18, 'BOL', 3, NULL, 14, 'BOL - 28/42/56/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (3, 19, 'BOL', 4, NULL, 30, 'BOL - 30/60/90/120/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (3, 20, 'BOL', 5, NULL, 7, 'BOL - 28/35/42/49/56/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (4, 21, 'CCD', 1, NULL, 30, 'CCD - 30/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (4, 22, 'CCD', 2, NULL, 30, 'CCD - 30/60/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (4, 23, 'CCD', 3, NULL, 30, 'CCD - 30/60/90/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (4, 24, 'CCD', 4, NULL, 30, 'CCD - 30/60/90/120/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (4, 25, 'CCD', 5, NULL, 30, 'CCD - 30/60/90/120/150/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (4, 26, 'CCD', 6, NULL, 30, 'CCD - 30/60/90/120/150/180/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (5, 27, 'CCL', 1, NULL, 1, 'CCL - 1/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT MC_FormaPag(CodFormaP, Codigo, FormaPag, Parcelas, Entrada, Intervalo, Condicao, Desconto, DescMaximo, TaxaAcrescimo, TarifaPadrao, TarifaAntecipacao, TarifaPadraoTipo) VALUES (6, 28, 'CDV', 1, NULL, 1, 'CDV - 1/DIAS', NULL, NULL, NULL, NULL, NULL, NULL)
GO