--
-- Script was generated by Devart dbForge Studio 2018 for SQL Server, Version 5.6.104.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 16/07/2020 14:32:14
-- Server version: 10.50.4000
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT MC_Grupo(Codigo, CodSetor, Nome, MargemLucro) VALUES (1, 1, 'BOTA', NULL)
INSERT MC_Grupo(Codigo, CodSetor, Nome, MargemLucro) VALUES (2, 1, 'LUVA', NULL)
INSERT MC_Grupo(Codigo, CodSetor, Nome, MargemLucro) VALUES (3, 1, 'OCULOS', NULL)
INSERT MC_Grupo(Codigo, CodSetor, Nome, MargemLucro) VALUES (4, 1, 'CAPACETE', NULL)
INSERT MC_Grupo(Codigo, CodSetor, Nome, MargemLucro) VALUES (5, 1, 'MACACAO', NULL)
INSERT MC_Grupo(Codigo, CodSetor, Nome, MargemLucro) VALUES (6, 1, 'PROTETOR AURICULAR', NULL)
INSERT MC_Grupo(Codigo, CodSetor, Nome, MargemLucro) VALUES (7, 1, 'PROTETOR SOLAR', NULL)
INSERT MC_Grupo(Codigo, CodSetor, Nome, MargemLucro) VALUES (8, 1, 'PROTETOR FACIAL', NULL)
INSERT MC_Grupo(Codigo, CodSetor, Nome, MargemLucro) VALUES (9, 1, 'CALCA', NULL)
INSERT MC_Grupo(Codigo, CodSetor, Nome, MargemLucro) VALUES (10, 1, 'COLETE', NULL)
INSERT MC_Grupo(Codigo, CodSetor, Nome, MargemLucro) VALUES (11, 1, 'CINTO', NULL)
INSERT MC_Grupo(Codigo, CodSetor, Nome, MargemLucro) VALUES (12, 2, 'CONE', NULL)
INSERT MC_Grupo(Codigo, CodSetor, Nome, MargemLucro) VALUES (13, 2, 'FITA ZEBRADA', NULL)
INSERT MC_Grupo(Codigo, CodSetor, Nome, MargemLucro) VALUES (14, 2, 'FITA ANTI-DERRAPANTE', NULL)
INSERT MC_Grupo(Codigo, CodSetor, Nome, MargemLucro) VALUES (15, 2, 'FITA DEMARCATORIA', NULL)
INSERT MC_Grupo(Codigo, CodSetor, Nome, MargemLucro) VALUES (16, 2, 'CORRENTE ZEBRADA', NULL)
INSERT MC_Grupo(Codigo, CodSetor, Nome, MargemLucro) VALUES (17, 2, 'PEDESTAL', NULL)
GO