--
-- Script was generated by Devart dbForge Studio 2018 for SQL Server, Version 5.6.104.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 16/07/2020 14:31:23
-- Server version: 10.50.4000
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT MC_Setor(Codigo, Nome, Markup, Tipo_Setor, GTouch) VALUES (1, 'EPI', NULL, 'V', NULL)
INSERT MC_Setor(Codigo, Nome, Markup, Tipo_Setor, GTouch) VALUES (2, 'EPC', NULL, 'V', NULL)
GO